version: '3'
services:
  postgresTestDB:
    image: postgres
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: on-failure
  postgresSecurityDB:
    image: postgres
    environment:
      - POSTGRES_DB=securityDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432
    restart: on-failure
  # rabbitMQ:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   restart: on-failure
  # elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    # container_name: elasticsearch
    # environment:
      # - discovery.type=single-node
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - ELASTIC_PASSWORD=changeme
      # - xpack.security.enabled=true
    # volumes:
      # - elasticsearch-data:/usr/share/elasticsearch/data
    # ports:
      # - 9200:9200
  # logstash:
    # image: logstash:7.17.1
    # container_name: logstash
    # ports:
      # - 4560:4560
      # - 4660:4660
    # privileged: true
    # environment:
      # - TZ=Asia/Shanghai
    # volumes:
      # - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    # depends_on:
      # - elasticsearch
  # kibana:
    # image: docker.elastic.co/kibana/kibana:7.12.0
    # container_name: kibana
    # environment:
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
      # - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    # ports:
      # - 5601:5601
    # depends_on:
      # - elasticsearch
# volumes:
  # elasticsearch-data:
    # driver: local