eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9003/oauth/check_token
    client:
      client-id: client
      client-secret: pass
      
