apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice-deploy
  labels:
    app: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
       - name: config-server-pod
         image: prabhatkumar/configservice:Latest
         ports:
          - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: configservice
  labels:
    app: config-server-service
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - port: 9000
      targetPort: 9000