apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deploy
  labels:
    app: eureka-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
       - name: eureka-server-pod
         image: prabhatkumar/eurekaservice:Latest
         ports:
          - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  labels:
    app: eureka-server
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - port: 9001
      targetPort: 9001