spring:
  application:
    name: eurekaservice
  profiles:
    active: default    
server:
  port: 10001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:10001/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5
     


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG