server:
  port: 9002

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:9001/eureka/

#
#
#  debug:
#    request: true
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
