server:
  port: 8082
example:
  organization:
    property: "I AM THE DEFAULT ORGANIZATION SERVICE"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: postgres
    testWhileIdle: 'true'
    validationQuery: SELECT 1