server:
  port: 8081
example:
  property: I AM THE DEFAULT
spring:
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresTestDB:5432/testDB
    username: postgres
    password: postgres
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaservice:9001/eureka/
      
security:
  oauth2:
    resource:
      token-info-uri: http://authorizationservice:9003/auth/oauth/check_token
    client:
      client-id: client
      client-secret: pass