server:
  port: 11081
example:
  property: I AM THE DEFAULT
spring:
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: postgres
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    
serviceConfig:
  jwtEnabled: true
  signingKey: 'secret'
  zuulLicensingserviceUrl: http://zuulservice/api/licensing
  zuulOrganizationserviceUrl: http://zuulservice/api/organization
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:10003/auth/oauth/check_token
    client:
      client-id: client
      client-secret: pass