server:
  port: 9003
spring:
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/securityDB
    username: postgres
    password: postgres
    testWhileIdle: 'true'
    validationQuery: SELECT 1